--- # my loops
- hosts: all
  become: yes
  connection: ssh
  tasks:
     - name: installing packages
       apt:
         name: "{{item}}"
         state: present
       loop: 
        -  nodejs
        -  php
